# Generated by Django 4.1.1 on 2022-11-29 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('castillo_barbara', '0002_pensamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensamiento',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pensamiento',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
